---
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        id: setup-beam
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore cached dependencies and build artifacts
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: mix-${{ runner.os }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.erlang-version }}-${{ hashFiles('**/mix.lock', 'config/config.exs', 'config/prod.exs') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.compile

      - name: Run static checks
        run: |
          mix format --check-formatted

      - name: Compile
        run: mix compile --warnings-as-errors
