---
name: 'Release'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-22.04

    env:
      MIX_ENV: prod

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore cached dependencies and build artifacts
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.erlang-version }}-${{ hashFiles('**/mix.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.compile

      - name: Create Release Package
        run: mix release

      - name: Deploy to DigitalOcean Droplet
        run: |
          echo -n $DEPLOY_HOST_PRIVATE_KEY | base64 -d > /tmp/deploy_host.pem
          chmod 0400 /tmp/deploy_host.pem
          tar -z -c -C _build/prod/rel tasky | ssh -o StrictHostKeyChecking=no -i /tmp/deploy_host.pem $DEPLOY_USER@$DEPLOY_HOST -- tar -z -x
        env:
          DEPLOY_HOST_PRIVATE_KEY: ${{ secrets.DEPLOY_HOST_PRIVATE_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
